### ISSUE TITLE
Uber JAR(Payara Micro)化、WildFly Swarm化

### ISSUE THREAD

**Issue by MasatoshiTada** [MasatoshiTada/jjug-action-based-mvc#3]
時間があればやる。

**Comment by MasatoshiTada** [comment]
Uber JAR化は完了。プログラムには一切変更なし。
起動用のシェルスクリプトを追加した。

**Comment by MasatoshiTada** [comment]
WildFly-Swarmはなんか動かなかった・・・。必要な依存性が足りてない？

```log
$ java -jar target/jjug-resteasy-html-swarm.jar 
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.wildfly.swarm.bootstrap.Main.invoke(Main.java:86)
        at org.wildfly.swarm.bootstrap.Main.run(Main.java:50)
        at org.wildfly.swarm.bootstrap.Main.main(Main.java:45)
Caused by: java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: org/wildfly/swarm/config/datasources/JDBCDriverConsumer
        at com.example.Main.newContainer(Main.java:25)
        at com.example.Main.main(Main.java:20)
        ... 7 more
Caused by: java.lang.NoClassDefFoundError: org/wildfly/swarm/config/datasources/JDBCDriverConsumer
        ... 9 more
Caused by: java.lang.ClassNotFoundException: org.wildfly.swarm.config.datasources.JDBCDriverConsumer from [Module "swarm.application:main" from BootModuleLoader@60285225 for finders [BootstrapClasspathModuleFinder, BootstrapModuleFinder(org.wildfly.swarm.bootstrap:main), ClasspathModuleFinder, ApplicationModuleFinder(swarm.application:main)]]
        at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:198)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:363)
        at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:351)
        at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:93)
        ... 9 more
```

**Comment by MasatoshiTada** [comment]
magさんのプルリクで、WildFly-Swarmも動いたのでクローズします。
